/**
This file is part of the Volta project.
Copyright (C) 2007-2013 Kai Berk Oezer
https://robo.fish/wiki/index.php?title=Volta
https://github.com/robo-fish/Volta

Volta is free software. You can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
#pragma once

/// Sent when the delete key is pressed on the outline view.
/// Notification object: The FXOutlineView instance that sends the notification
extern NSString* FXOutlineViewDeleteKeyNotification;


/// This customization of NSOutlineView provides enhancements like:
/// - sending a notification when the delete key is pressed,
/// - collapsing/expanding items when double clicked on,
/// - ability to set a custom image for dragging
///
@interface FXOutlineView : NSOutlineView

/// If the drag image is nil then the default drag image (generated by NSOutlineView) will be used.
@property NSImage* dragImage;

@end

