/**
This file is part of the Volta project.
Copyright (C) 2007-2013 Kai Berk Oezer
https://robo.fish/wiki/index.php?title=Volta
https://github.com/robo-fish/Volta

Volta is free software. You can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef FX_TABLE_VIEW_H
#define FX_TABLE_VIEW_H


/// A notification that is sent when the delete key is pressed on the table view.
extern NSString* FXTableViewDeleteKeyNotification;

/// This customization of NSTableView adds the following capabilities
///  - Posting FXTableViewDeleteKeyNotification when the delete key is pressed,
///  - Ability to set a custom drag image
///
@interface FXTableView : NSTableView

/// If the drag image is nil then the default drag image (generated by NSTableView) will be used.
@property NSImage* dragImage;

@end


#endif // FX_TABLE_VIEW_H
